/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.1 		*/
/*  Created On : 25-mar-2026 20:13:24 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

ALTER TABLE [DiscordBot] DROP CONSTRAINT [FK_Discord Bot_wymiana danych w celu skonfigurowania konta];

ALTER TABLE [DiscordSerwer] DROP CONSTRAINT [FK_Discord serwer_zawiera];

ALTER TABLE [NotatkaAnalogowa] DROP CONSTRAINT [FK_Notatka analogowa_przyjmuje];

ALTER TABLE [NotatkaAnalogowa] DROP CONSTRAINT [FK_Notatka analogowa_tworzy];

ALTER TABLE [NotatkaMarkdown] DROP CONSTRAINT [FK_Notatka Markdown_wyświetla];

ALTER TABLE [NotatkaMarkdown] DROP CONSTRAINT [FK_Notatka Markdown_wytwarza];

ALTER TABLE [Obsidian] DROP CONSTRAINT [FK_Obsidian_obsługuje];

ALTER TABLE [Obsidian] DROP CONSTRAINT [FK_Obsidian_korzysta];

ALTER TABLE [ZapleczePrzetwarzająceNotatki] DROP CONSTRAINT [FK_Zaplecze przetwarzające notatki_składa się z];

ALTER TABLE [ZapleczeSystemuNotesAi] DROP CONSTRAINT [FK_Zaplecze systemu notes AI_składa się z];

DROP TABLE [AplikacjaObsidian];

DROP TABLE [BotDiscord];

DROP TABLE [DiscordBot];

DROP TABLE [DiscordSerwer];

DROP TABLE [KolejkaZdjęć];

DROP TABLE [LokalizacjaZapisuNotatekMarkdown];

DROP TABLE [NotatkaAnalogowa];

DROP TABLE [NotatkaMarkdown];

DROP TABLE [Obsidian];

DROP TABLE [SilnikDoInferencjiDużychModeliJęzykowych];

DROP TABLE [Użytkownik];

DROP TABLE [Użytkownik];

DROP TABLE [ZapleczePrzetwarzająceNotatki];

DROP TABLE [ZapleczeSystemuNotesAi];

CREATE TABLE [AplikacjaObsidian]
(
	[AplikacjaObsidianID] varchar NOT NULL
);

CREATE TABLE [BotDiscord]
(
	[BotDiscordID] varchar NOT NULL
);

CREATE TABLE [DiscordBot]
(
	[Id] varchar NULL,
	[Nazwa] varchar NULL,
	[DiscordBotID] varchar NOT NULL,
	[UżytkownikID] varchar NULL
);

CREATE TABLE [DiscordSerwer]
(
	[Nazwa] varchar NULL,
	[Typ] varchar NULL,
	[DiscordSerwerID] varchar NOT NULL,
	[DiscordBotID] varchar NOT NULL
);

CREATE TABLE [KolejkaZdjęć]
(
	[KolejkaZdjęćID] varchar NOT NULL
);

CREATE TABLE [LokalizacjaZapisuNotatekMarkdown]
(
	[LokalizacjaZapisuNotatekMarkdownID] varchar NOT NULL
);

CREATE TABLE [NotatkaAnalogowa]
(
	[TypNotatki] varchar NULL,
	[NotatkaAnalogowaID] varchar NOT NULL,
	[BotDiscordID] varchar NOT NULL,
	[UżytkownikID] varchar NOT NULL
);

CREATE TABLE [NotatkaMarkdown]
(
	[NotatkaMarkdownID] varchar NOT NULL,
	[AplikacjaObsidianID] varchar NULL,
	[ZapleczePrzetwarzająceNotatkiID] varchar NOT NULL
);

CREATE TABLE [Obsidian]
(
	[Wersja] varchar NULL,
	[ObsidianID] varchar NOT NULL,
	[LokalizacjaZapisuNotatekMarkdownID] varchar NOT NULL,
	[UżytkownikID] varchar NOT NULL
);

CREATE TABLE [SilnikDoInferencjiDużychModeliJęzykowych]
(
	[SilnikDoInferencjiDużychModeliJęzykowychID] varchar NOT NULL
);

CREATE TABLE [Użytkownik]
(
	[Nazwa] varchar NULL,
	[UżytkownikID] varchar NOT NULL
);

CREATE TABLE [Użytkownik]
(
	[Id] varchar NULL,
	[Nazwa] varchar NULL,
	[UżytkownikID] varchar NOT NULL
);

CREATE TABLE [ZapleczePrzetwarzająceNotatki]
(
	[ZapleczePrzetwarzająceNotatkiID] varchar NOT NULL,
	[BotDiscordID] varchar NOT NULL,
	[KolejkaZdjęćID] varchar NOT NULL,
	[SilnikDoInferencjiDużychModeliJęzykowychID] varchar NOT NULL
);

CREATE TABLE [ZapleczeSystemuNotesAi]
(
	[ZapleczeSystemuNotesAiID] varchar NOT NULL,
	[DiscordBotID] varchar NOT NULL
);

ALTER TABLE [AplikacjaObsidian] ADD CONSTRAINT [PK_AplikacjaObsidian]
	PRIMARY KEY ([AplikacjaObsidianID]);

ALTER TABLE [BotDiscord] ADD CONSTRAINT [PK_BotDiscord]
	PRIMARY KEY ([BotDiscordID]);

ALTER TABLE [DiscordBot] ADD CONSTRAINT [PK_DiscordBot]
	PRIMARY KEY ([DiscordBotID]);

ALTER TABLE [DiscordSerwer] ADD CONSTRAINT [PK_DiscordSerwer]
	PRIMARY KEY ([DiscordSerwerID]);

ALTER TABLE [KolejkaZdjęć] ADD CONSTRAINT [PK_KolejkaZdjęć]
	PRIMARY KEY ([KolejkaZdjęćID]);

ALTER TABLE [LokalizacjaZapisuNotatekMarkdown] ADD CONSTRAINT [PK_LokalizacjaZapisuNotatekMarkdown]
	PRIMARY KEY ([LokalizacjaZapisuNotatekMarkdownID]);

ALTER TABLE [NotatkaAnalogowa] ADD CONSTRAINT [PK_NotatkaAnalogowa]
	PRIMARY KEY ([NotatkaAnalogowaID]);

ALTER TABLE [NotatkaMarkdown] ADD CONSTRAINT [PK_NotatkaMarkdown]
	PRIMARY KEY ([NotatkaMarkdownID]);

ALTER TABLE [Obsidian] ADD CONSTRAINT [PK_Obsidian]
	PRIMARY KEY ([ObsidianID]);

ALTER TABLE [SilnikDoInferencjiDużychModeliJęzykowych] ADD CONSTRAINT [PK_SilnikDoInferencjiDużychModeliJęzykowych]
	PRIMARY KEY ([SilnikDoInferencjiDużychModeliJęzykowychID]);

ALTER TABLE [Użytkownik] ADD CONSTRAINT [PK_Użytkownik]
	PRIMARY KEY ([UżytkownikID]);

ALTER TABLE [Użytkownik] ADD CONSTRAINT [PK_Użytkownik]
	PRIMARY KEY ([UżytkownikID]);

ALTER TABLE [ZapleczePrzetwarzająceNotatki] ADD CONSTRAINT [PK_ZapleczePrzetwarzająceNotatki]
	PRIMARY KEY ([ZapleczePrzetwarzająceNotatkiID]);

ALTER TABLE [ZapleczeSystemuNotesAi] ADD CONSTRAINT [PK_ZapleczeSystemuNotesAi]
	PRIMARY KEY ([ZapleczeSystemuNotesAiID]);

ALTER TABLE [DiscordBot] ADD CONSTRAINT [FK_Discord Bot_wymiana danych w celu skonfigurowania konta]
	FOREIGN KEY ([UżytkownikID]) REFERENCES [Użytkownik] ([UżytkownikID]);

ALTER TABLE [DiscordSerwer] ADD CONSTRAINT [FK_Discord serwer_zawiera]
	FOREIGN KEY ([DiscordBotID]) REFERENCES [DiscordBot] ([DiscordBotID]);

ALTER TABLE [NotatkaAnalogowa] ADD CONSTRAINT [FK_Notatka analogowa_przyjmuje]
	FOREIGN KEY ([BotDiscordID]) REFERENCES [BotDiscord] ([BotDiscordID]);

ALTER TABLE [NotatkaAnalogowa] ADD CONSTRAINT [FK_Notatka analogowa_tworzy]
	FOREIGN KEY ([UżytkownikID]) REFERENCES [Użytkownik] ([UżytkownikID]);

ALTER TABLE [NotatkaMarkdown] ADD CONSTRAINT [FK_Notatka Markdown_wyświetla]
	FOREIGN KEY ([AplikacjaObsidianID]) REFERENCES [AplikacjaObsidian] ([AplikacjaObsidianID]);

ALTER TABLE [NotatkaMarkdown] ADD CONSTRAINT [FK_Notatka Markdown_wytwarza]
	FOREIGN KEY ([ZapleczePrzetwarzająceNotatkiID]) REFERENCES [ZapleczePrzetwarzająceNotatki] ([ZapleczePrzetwarzająceNotatkiID]);

ALTER TABLE [Obsidian] ADD CONSTRAINT [FK_Obsidian_obsługuje]
	FOREIGN KEY ([LokalizacjaZapisuNotatekMarkdownID]) REFERENCES [LokalizacjaZapisuNotatekMarkdown] ([LokalizacjaZapisuNotatekMarkdownID]);

ALTER TABLE [Obsidian] ADD CONSTRAINT [FK_Obsidian_korzysta]
	FOREIGN KEY ([UżytkownikID]) REFERENCES [Użytkownik] ([UżytkownikID]);

ALTER TABLE [ZapleczePrzetwarzająceNotatki] ADD CONSTRAINT [FK_Zaplecze przetwarzające notatki_składa się z]
	FOREIGN KEY ([BotDiscordID]) REFERENCES [BotDiscord] ([BotDiscordID]);

ALTER TABLE [ZapleczeSystemuNotesAi] ADD CONSTRAINT [FK_Zaplecze systemu notes AI_składa się z]
	FOREIGN KEY ([DiscordBotID]) REFERENCES [DiscordBot] ([DiscordBotID]);
