///////////////////////////////////////////////////////////
//  DiscordAPI_WyœlijPowiadomienie.cs
//  Implementation of the Class DiscordAPI_WyœlijPowiadomienie
//  Generated by Enterprise Architect
//  Created on:      25-mar-2026 20:09:40
//  Original author: Adrian Cieœla
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DiscordAPI_WyœlijPowiadomienie {

	private Typ powiadomienia typ powiadomienia;

	public DiscordAPI_WyœlijPowiadomienie(){

	}

	~DiscordAPI_WyœlijPowiadomienie(){

	}

}//end DiscordAPI_WyœlijPowiadomienie