///////////////////////////////////////////////////////////
//  Papier_ZapiszTagNOTE.cs
//  Implementation of the Class Papier_ZapiszTagNOTE
//  Generated by Enterprise Architect
//  Created on:      25-mar-2026 20:10:04
//  Original author: Adrian Cieœla
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Papier_ZapiszTagNOTE {

	private char zawartoœæ tagu NOTE;

	public Papier_ZapiszTagNOTE(){

	}

	~Papier_ZapiszTagNOTE(){

	}

	public Ster_ZapiszTagNOTE Ster_ZapiszTagNOTE{
		get{
			return m_Ster_ZapiszTagNOTE;
		}
		set{
			m_Ster_ZapiszTagNOTE = value;
		}
	}

}//end Papier_ZapiszTagNOTE