///////////////////////////////////////////////////////////
//  DiscordApi_WyœlijWiadomoœæ.cs
//  Implementation of the Class DiscordApi_WyœlijWiadomoœæ
//  Generated by Enterprise Architect
//  Created on:      25-mar-2026 20:09:46
//  Original author: Adrian Cieœla
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class DiscordApi_WyœlijWiadomoœæ {

	private char tekst;
	private binary za³¹czone zdjêcia;

	public DiscordApi_WyœlijWiadomoœæ(){

	}

	~DiscordApi_WyœlijWiadomoœæ(){

	}

	public Ster_WyœlijWiadomoœæ Ster_WyœlijWiadomoœæ{
		get{
			return m_Ster_WyœlijWiadomoœæ;
		}
		set{
			m_Ster_WyœlijWiadomoœæ = value;
		}
	}

}//end DiscordApi_WyœlijWiadomoœæ