///////////////////////////////////////////////////////////
//  Typ powiadomienia.cs
//  Implementation of the Enumeration Typ powiadomienia
//  Generated by Enterprise Architect
//  Created on:      25-mar-2026 20:10:09
//  Original author: Adrian Cieœla
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum Typ powiadomienia : int {

	sukces,
	b³¹d

}//end Typ powiadomienia