///////////////////////////////////////////////////////////
//  ObsydianCLI_ZapiszPlik.cs
//  Implementation of the Class ObsydianCLI_ZapiszPlik
//  Generated by Enterprise Architect
//  Created on:      25-mar-2026 20:09:59
//  Original author: Adrian Cieœla
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ObsydianCLI_ZapiszPlik {

	private char zawartoœæ pliku;

	public ObsydianCLI_ZapiszPlik(){

	}

	~ObsydianCLI_ZapiszPlik(){

	}

}//end ObsydianCLI_ZapiszPlik